### PR TITLE
Colors now share the same color.

### PR DESCRIPTION
**Pull request by Joshua-Dunne**
### What Changed
Primary Color for the App Design has been changed to lightGreen[900].

### Please Look At
The App Bar and anything that uses a primary color. Make sure they are all lightGreen[900].
In short, the old blue default should no longer exist. If you find one, let me know and I will change it to meet the current green color.

### CODE REVIEW

**Review by Richard-Fleming — APPROVED** [review]
LGTM

**Comment by Joshua-Dunne** [comment]
> 
> 
> LGTM

LGTM

**Comment by Joshua-Dunne** [comment]
help

**Comment by Joshua-Dunne** [comment]
how  i mrug

**Review by MichalKrzyzanowski — APPROVED** [review]
LGTM

**Comment by Joshua-Dunne** [comment]
a

**Comment by Joshua-Dunne** [comment]
LGTM

**Pull request merged**
